/****************************************************************************
 *
 * IndiFlo Ground Control
 *
 * IndiFlo Message Notification Box
 *
 * Directly integrated with QGroundControl Vehicle StatusTextHandler
 *
 ****************************************************************************/

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

import QGroundControl
import QGroundControl.Controls
import QGroundControl.FactSystem
import QGroundControl.ScreenTools
import QGroundControl.Palette

Rectangle {
    id: root

    // =========================================================
    // POSITION
    // =========================================================

    /*
     * Position is controlled here only when this component
     * itself is not anchored by the parent.
     *
     * If FlyView gives this component anchors.top, those
     * anchors will take precedence.
     */
    y: 350

    anchors.right: parent ? parent.right : undefined
    anchors.rightMargin: 18

    // =========================================================
    // SIZE
    // =========================================================

    width: 280
    height: expanded ? 220 : 48

    radius: 14

    color: "#D9151B22"

    border.width: 1

    // Border follows QGC's actual message severity.
    border.color:
        _activeVehicle && _activeVehicle.messageTypeError
        ? "#AAFF3030"
        : _activeVehicle && _activeVehicle.messageTypeWarning
          ? "#AAFFB020"
          : "#45FFFFFF"

    clip: true

    // =========================================================
    // PROPERTIES
    // =========================================================

    property bool expanded: true

    property var _activeVehicle:
        QGroundControl.multiVehicleManager.activeVehicle

    /*
     * THIS IS THE IMPORTANT PART.
     *
     * We are reading the exact same QGC message property
     * used by VehicleMessageList.qml.
     */
    property bool noMessages:
        !_activeVehicle ||
        !_activeVehicle.formattedMessages ||
        _activeVehicle.formattedMessages.length === 0

    property int messageCount:
        _activeVehicle
        ? _activeVehicle.messageCount
        : 0

    property bool hasError:
        _activeVehicle &&
        _activeVehicle.messageTypeError

    property bool hasWarning:
        _activeVehicle &&
        _activeVehicle.messageTypeWarning

    property bool hasNormal:
        _activeVehicle &&
        _activeVehicle.messageTypeNormal

    // =========================================================
    // PALETTE
    // =========================================================

    QGCPalette {
        id: qgcPal
        colorGroupEnabled: true
    }

    // =========================================================
    // FACT CONTROLLER
    //
    // This preserves QGC's param:// links inside messages.
    // =========================================================

    FactPanelController {
        id: controller
    }

    property var _fact: null

    // =========================================================
    // QGC MESSAGE FORMATTER
    // =========================================================

    /*
     * This follows the same severity markers generated by
     * StatusTextHandler:
     *
     * <#E> = Error / Critical / Alert / Emergency
     * <#I> = Warning / Notice
     * <#N> = Normal / Info
     *
     * We are NOT guessing severity from message text.
     *
     * QGC already classified the MAVLink severity before
     * the message reached this component.
     */
    function formatMessage(message) {

        if (!message) {
            return ""
        }

        var formatted = String(message)

        // =====================================================
        // ERROR / CRITICAL
        // =====================================================

        formatted = formatted.replace(
            new RegExp("<#E>", "g"),
            "color: #FF5252; font-weight: bold;"
        )

        // =====================================================
        // WARNING / NOTICE
        // =====================================================

        formatted = formatted.replace(
            new RegExp("<#I>", "g"),
            "color: #FFB020; font-weight: bold;"
        )

        // =====================================================
        // NORMAL / INFORMATION
        // =====================================================

        formatted = formatted.replace(
            new RegExp("<#N>", "g"),
            "color: #D9E2EA;"
        )

        return formatted
    }

    // =========================================================
    // UPDATE MESSAGE DISPLAY
    // =========================================================

    function updateMessages() {

        if (!_activeVehicle) {
            messageDisplay.text = ""
            return
        }

        /*
         * EXACT QGC SOURCE:
         *
         * Vehicle::formattedMessages()
         *
         * which comes from StatusTextHandler.
         */
        messageDisplay.text =
            formatMessage(
                _activeVehicle.formattedMessages
            )
    }

    // =========================================================
    // CLEAR DISPLAY
    // =========================================================

    function clearDisplay() {
        messageDisplay.clear()
    }

    // =========================================================
    // HEIGHT ANIMATION
    // =========================================================

    Behavior on height {

        NumberAnimation {
            duration: 180
            easing.type: Easing.OutCubic
        }
    }

    // =========================================================
    // HEADER
    // =========================================================

    Rectangle {
        id: header

        anchors.left: parent.left
        anchors.right: parent.right
        anchors.top: parent.top

        height: 48

        color: "transparent"

        RowLayout {

            anchors.fill: parent

            anchors.leftMargin: 12
            anchors.rightMargin: 8

            spacing: 7

            // =================================================
            // STATUS INDICATOR
            // =================================================

            Rectangle {

                Layout.preferredWidth: 9
                Layout.preferredHeight: 9

                radius: 4.5

                color:
                    root.hasError
                    ? "#FF3030"
                    : root.hasWarning
                      ? "#FFB020"
                      : root.noMessages
                        ? "#55FFFFFF"
                        : "#66BFFF"

                // Error = fastest pulse
                // Warning = medium pulse
                // Message = slow pulse
                SequentialAnimation on opacity {

                    running:
                        root.hasError ||
                        root.hasWarning ||
                        !root.noMessages

                    loops: Animation.Infinite

                    NumberAnimation {
                        from: 1.0
                        to: 0.35

                        duration:
                            root.hasError
                            ? 350
                            : root.hasWarning
                              ? 550
                              : 900
                    }

                    NumberAnimation {
                        from: 0.35
                        to: 1.0

                        duration:
                            root.hasError
                            ? 350
                            : root.hasWarning
                              ? 550
                              : 900
                    }
                }
            }

            // =================================================
            // TITLE
            // =================================================

            Text {

                Layout.fillWidth: true

                text:
                    root.hasError
                    ? "CRITICAL / ERROR"
                    : root.hasWarning
                      ? "WARNINGS"
                      : "MESSAGES"

                color:
                    root.hasError
                    ? "#FF6B6B"
                    : root.hasWarning
                      ? "#FFD166"
                      : "white"

                font.bold: true
                font.pixelSize: 12
                font.letterSpacing: 1.0

                verticalAlignment:
                    Text.AlignVCenter

                elide:
                    Text.ElideRight
            }

            // =================================================
            // ACTUAL QGC MESSAGE COUNT
            // =================================================

            Rectangle {

                Layout.preferredWidth: 27
                Layout.preferredHeight: 23

                radius: 7

                color:
                    root.hasError
                    ? "#45FF3030"
                    : root.hasWarning
                      ? "#45FFB020"
                      : "#18FFFFFF"

                border.width: 1

                border.color:
                    root.hasError
                    ? "#70FF3030"
                    : root.hasWarning
                      ? "#70FFB020"
                      : "#25FFFFFF"

                Text {

                    anchors.centerIn: parent

                    text:
                        root.messageCount > 99
                        ? "99+"
                        : String(root.messageCount)

                    color:
                        root.hasError
                        ? "#FF6B6B"
                        : root.hasWarning
                          ? "#FFD166"
                          : "#D9E2EA"

                    font.bold: true
                    font.pixelSize: 10
                }
            }

            // =================================================
            // CLEAR BUTTON
            // =================================================

            Rectangle {

                Layout.preferredWidth: 28
                Layout.preferredHeight: 28

                radius: 7

                color:
                    clearMouseArea.pressed
                    ? "#45FFFFFF"
                    : "#18FFFFFF"

                border.width: 1
                border.color: "#25FFFFFF"

                Text {

                    anchors.centerIn: parent

                    text: "×"

                    color: "white"

                    font.pixelSize: 18
                }

                MouseArea {

                    id: clearMouseArea

                    anchors.fill: parent

                    hoverEnabled: true

                    onClicked: {

                        if (root._activeVehicle) {

                            /*
                             * Use the SAME QGC clear operation.
                             *
                             * This clears the underlying
                             * StatusTextHandler message list.
                             */
                            root._activeVehicle.clearMessages()

                            root.clearDisplay()
                        }
                    }
                }

                ToolTip.visible:
                    containsMouse

                ToolTip.text:
                    "Clear messages"
            }

            // =================================================
            // EXPAND / COLLAPSE BUTTON
            // =================================================

            Rectangle {

                Layout.preferredWidth: 28
                Layout.preferredHeight: 28

                radius: 7

                color:
                    expandMouseArea.pressed
                    ? "#45FFFFFF"
                    : "#18FFFFFF"

                border.width: 1
                border.color: "#25FFFFFF"

                Text {

                    anchors.centerIn: parent

                    text:
                        root.expanded
                        ? "⌃"
                        : "⌄"

                    color: "white"

                    font.pixelSize: 17
                }

                MouseArea {

                    id: expandMouseArea

                    anchors.fill: parent

                    hoverEnabled: true

                    onClicked: {
                        root.expanded =
                            !root.expanded
                    }
                }

                ToolTip.visible:
                    containsMouse

                ToolTip.text:
                    root.expanded
                    ? "Collapse messages"
                    : "Expand messages"
            }
        }
    }

    // =========================================================
    // MESSAGE AREA
    // =========================================================

    Rectangle {

        id: messageBackground

        visible:
            root.expanded

        anchors.left:
            parent.left

        anchors.right:
            parent.right

        anchors.top:
            header.bottom

        anchors.bottom:
            parent.bottom

        anchors.leftMargin:
            7

        anchors.rightMargin:
            7

        anchors.bottomMargin:
            7

        radius:
            9

        color:
            root.hasError
            ? "#B51A0808"
            : root.hasWarning
              ? "#B5141005"
              : "#B5090E14"

        border.width:
            1

        border.color:
            root.hasError
            ? "#55FF3030"
            : root.hasWarning
              ? "#55FFB020"
              : "#20FFFFFF"

        clip:
            true

        // =====================================================
        // SCROLL VIEW
        // =====================================================

        ScrollView {

            id: messageScroll

            anchors.fill:
                parent

            anchors.margins:
                6

            clip:
                true

            ScrollBar.vertical.policy:
                ScrollBar.AsNeeded

            // =================================================
            // MESSAGE TEXT
            // =================================================

            TextArea {

                id: messageDisplay

                width:
                    messageScroll.availableWidth

                readOnly:
                    true

                textFormat:
                    TextEdit.RichText

                wrapMode:
                    TextEdit.Wrap

                color:
                    qgcPal.text

                font.pixelSize:
                    11

                selectByMouse:
                    true

                padding:
                    4

                background:
                    Rectangle {
                        color: "transparent"
                    }

                placeholderText:
                    root._activeVehicle
                    ? qsTr("No Messages")
                    : qsTr("No vehicle connected")

                placeholderTextColor:
                    "#90FFFFFF"

                // =============================================
                // INITIALIZATION
                // =============================================

                Component.onCompleted: {

                    root.updateMessages()
                }

                // =============================================
                // EXACT QGC NEW MESSAGE SIGNAL
                // =============================================

                Connections {

                    target:
                        root._activeVehicle

                    /*
                     * This is the SAME signal used by
                     * QGC's VehicleMessageList.qml.
                     *
                     * Every new MAVLink status message which
                     * reaches Vehicle is forwarded here.
                     */
                    function onNewFormattedMessage(
                        formattedMessage
                    ) {

                        if (!formattedMessage) {
                            return
                        }

                        messageDisplay.insert(
                            0,
                            root.formatMessage(
                                formattedMessage
                            )
                        )
                    }
                }

                // =============================================
                // ACTIVE VEHICLE CHANGED
                // =============================================

                Connections {

                    target:
                        QGroundControl.multiVehicleManager

                    function onActiveVehicleChanged() {

                        root.updateMessages()
                    }
                }
            }
        }
    }

    // =========================================================
    // NO VEHICLE MESSAGE
    // =========================================================

    Text {

        visible:
            root.expanded &&
            !root._activeVehicle

        anchors.centerIn:
            messageBackground

        text:
            "No vehicle connected"

        color:
            "#90FFFFFF"

        font.pixelSize:
            11
    }

    // =========================================================
    // NO MESSAGES
    // =========================================================

    Text {

        visible:
            root.expanded &&
            root._activeVehicle &&
            root.noMessages

        anchors.centerIn:
            messageBackground

        text:
            "No Messages"

        color:
            "#70FFFFFF"

        font.pixelSize:
            11
    }

    // =========================================================
    // ERROR INDICATOR
    // =========================================================

    Rectangle {

        visible:
            root.expanded &&
            root.hasError

        anchors.left:
            parent.left

        anchors.right:
            parent.right

        anchors.bottom:
            parent.bottom

        height:
            3

        color:
            "#FF3030"

        opacity:
            0.9

        SequentialAnimation on opacity {

            running:
                root.hasError

            loops:
                Animation.Infinite

            NumberAnimation {
                from: 0.25
                to: 1.0
                duration: 400
            }

            NumberAnimation {
                from: 1.0
                to: 0.25
                duration: 400
            }
        }
    }

    // =========================================================
    // WARNING INDICATOR
    // =========================================================

    Rectangle {

        visible:
            root.expanded &&
            !root.hasError &&
            root.hasWarning

        anchors.left:
            parent.left

        anchors.right:
            parent.right

        anchors.bottom:
            parent.bottom

        height:
            3

        color:
            "#FFB020"

        opacity:
            0.9
    }

    // =========================================================
    // QGC PARAMETER LINK SUPPORT
    // =========================================================

    Connections {

        target:
            messageDisplay

        function onLinkActivated(link) {

            if (link.startsWith("param://")) {

                var paramName =
                    link.substr(8)

                root._fact =
                    controller.getParameterFact(
                        -1,
                        paramName,
                        true
                    )

                if (root._fact !== null) {

                    paramEditorDialogComponent
                        .createObject(mainWindow)
                        .open()
                }

            } else {

                Qt.openUrlExternally(link)
            }
        }
    }

    // =========================================================
    // PARAMETER EDITOR
    // =========================================================

    Component {

        id:
            paramEditorDialogComponent

        ParameterEditorDialog {

            title:
                qsTr("Edit Parameter")

            fact:
                root._fact

            destroyOnClose:
                true
        }
    }
}
